### ISSUE TITLE
Add adsorption site to gasdb adsorption 

### ISSUE THREAD

**Issue by apalizha** [ulissigroup/GASpy#64]

**Comment by apalizha** [comment]
In mongo database, data in adsorption doesn't have an explicit adsorption_site as a descriptor.  It's under initial configuration.atoms.atoms.position. Versus atoms and catalog have it under FW_name.

**Comment by ktran9891** [comment]
The `atoms` collection has in under `fwname`, but the `catalog` collection has it in `processed_data.calculation_info.adsorption_site`.

What Pari is looking for is to have `get_adsorption_docs` return `adsorption_site` as a key/value pair. Since the adsorption site is not explicitly listed in the `adsorption` collection, she needs to parse it out of the data structure.

The easy way to do this is to assume that the first atom in the system is the binding atom so that we can just find its location. If we do, this'd be a simple change to `gaspy.defaults.adsorption_fingerprints`. This also relies on assuming that the first atom is the binding atom, which has a chance of biting us later if we ever change this.

**Comment by zulissi** [comment]
Maybe we should just add it to the adsorption collection? Should be a quick
change in whatever makes the document (dumptoadsorptiondb?)

**Comment by ktran9891** [comment]
I think either of those methods would still rely on the assumption that the first atom is the binding atom. But the first method seems easier, since we wouldn't have to regenerate our adsorption collection.

**Comment by ktran9891** [comment]
Added Pari to it because this'd be a good commit for her to tag along with.

**Comment by ktran9891** [comment]
[This commit](https://github.com/ulissigroup/GASpy/commit/39ca4e4f567073f69c532cda0a17f13698c4703e#diff-73f19772f342eb8e2e1b34286c5cdeef) addressed this issue.
