### ISSUE TITLE
is it possible to remove the dependence Docker?

### ISSUE THREAD

**Issue by XinyuuLi** [ulissigroup/GASpy#77]
Hi Kevin and Zachary,

Thanks for this interesting repo. 
I am trying to install this on my univeristy HPC. My HPC administrator suggested me to do this without Docker, since "Running a container on a HPC system where you don’t have root or cannot installed software is tricky". 
Can you plase suggest if it is possible to remove the Docker as dependence in this case?

Thanks.

**Comment by ktran9891** [comment]
Xinyu,

We will be continuing to depend on Docker, but there are two possible solutions for you.

1. You could request that your HPC administrator begin using [shifter](https://github.com/NERSC/shifter) instead of Docker. [NERSC](https://www.nersc.gov/) created it specifically so they could allow users of HPCs to run Docker containers without `sudo`.
2. If they cannot use shifter, then I suggest creating a [miniconda](https://docs.conda.io/en/latest/miniconda.html) environment with the appropriate dependencies. Our [dockerfile](https://github.com/ulissigroup/GASpy/blob/master/dockerfile/Dockerfile) shows you exactly how we install our dependencies. Lines 34–57 may prove especially useful for you.
