### ISSUE TITLE
First four atoms operators tests now failing

### ISSUE THREAD

**Issue by ktran9891** [ulissigroup/GASpy#98]
Everything runs without an error triggering, but the atomic positions seem to be off. Maybe something is up with pymatgen versioning?

**Comment by apalizha** [comment]
verified with Kevin and made changes to corresponding baseline pickle files. Because the slabs we have are periodic, the baseline slabs had some atoms coordination off by 1 unit cell (in X or Y direction). There was nothing fundamentally wrong with our slab generation. Changes are made and pushed to GASpy debug branch.

**Comment by ktran9891** [comment]
Fixed by #99
